# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_reaper', '0009_achievement_bonus_wheat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='checking_task',
        ),
        migrations.AddField(
            model_name='package',
            name='checking_function',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='function1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='function1', to='code_reaper.Function'),
        ),
        migrations.AddField(
            model_name='package',
            name='function2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='function2', to='code_reaper.Function'),
        ),
        migrations.AddField(
            model_name='package',
            name='function3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='function3', to='code_reaper.Function'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (3, 'Trusted'), (4, 'Not trusted')], default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='task1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task1', to='code_reaper.Task'),
        ),
        migrations.AlterField(
            model_name='package',
            name='task2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task2', to='code_reaper.Task'),
        ),
        migrations.AlterField(
            model_name='package',
            name='task3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task3', to='code_reaper.Task'),
        ),
    ]
