# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_reaper', '0010_auto_20180201_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='task1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task1', to='code_reaper.Task'),
        ),
        migrations.AlterField(
            model_name='package',
            name='task2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task2', to='code_reaper.Task'),
        ),
        migrations.AlterField(
            model_name='package',
            name='task3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task3', to='code_reaper.Task'),
        ),
    ]
