# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Function', max_length=200)),
                ('project', models.CharField(default='Project', max_length=200)),
                ('class_name', models.CharField(default='Class', max_length=200)),
                ('body', models.TextField()),
                ('lines_nr', models.IntegerField(default=0)),
                ('signs_nr', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grayed_out_lines', models.CharField(max_length=200)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_reaper.Function')),
            ],
        ),
    ]
