# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_reaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='lines_nr1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='grayed_out',
        ),
    ]
