# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:56
from __future__ import unicode_literals

import code_reaper.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_reaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('lines_nr', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grayed_out_lines', code_reaper.models.CommaSepField()),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_reaper.Function')),
            ],
        ),
    ]
