# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reaper', '0002_function_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='class_name',
            field=models.CharField(default='Class', max_length=200),
        ),
        migrations.AddField(
            model_name='function',
            name='name',
            field=models.CharField(default='Function', max_length=200),
        ),
    ]
