# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reaper', '0002_auto_20171111_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='function',
            name='signs_nr',
            field=models.IntegerField(default=0),
        ),
    ]
