# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reaper', '0003_auto_20171125_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='project',
            field=models.CharField(default='Project', max_length=200),
        ),
    ]
