# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reaper', '0011_auto_20180201_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
